# Deep learning

## numpy

In [3]:
import numpy as np

In [4]:
a = [[1,2],[3,4],[5,6],[7,8]]
b = np.array(a)

### np.array(ARRAY)로 만들어진 것의 정체

In [5]:
type(b)

numpy.ndarray

b는 ndarray 객체다.  
b 행렬의 특성을 알고 싶다면 메소드가 아닌 프로퍼티로 접근  
=> b.shape

## 넘파이 객체 생성

### X = shape

In [6]:
c = np.zeros((3,4)) #.ones() .eye()
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### X = about 등차수열
불완전한 키워드를 왜 썼을까 arange, linspace

In [7]:
d = np.arange(5)
d
# or np.arange(1, 10, 2) <= 시작, 끝, d 등차수열

array([0, 1, 2, 3, 4])

In [8]:
# 시작~끝을 n-1등분으로 표현, n개 결과값
e = np.linspace(0,10,10)
e

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## 넘파이 객체 변형

## Concatenate()

In [9]:
f = np.array([[1,2],[3,4]])
g = np.array([[5,6],[7,8]])

In [10]:
f

array([[1, 2],
       [3, 4]])

In [11]:
g

array([[5, 6],
       [7, 8]])

### numpy식 array 표기에서 시작

axis = 0(행방향) -> 위아래 이어붙이기

In [12]:
np.concatenate((f,g), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

axis = 1(열방향) -> 양옆 이어붙이기

In [13]:
np.concatenate((f,g), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

vstack -> vertical하게 쌓음  
hstack -> horizontal하게 쌓음

In [14]:
np.vstack((f,g))
np.hstack((f,g))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Reshape()

ndim 변경

In [15]:
h = np.arange(8)
h.shape

(8,)

In [16]:
i = h.reshape(2,4)
i

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
k = h.reshape(4,-1)
k

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### split()

In [18]:
array = np.arange(10,40,1).reshape(-1,10)
array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

np.split(ARRAY, INDEX(index-1까지 커팅), AXIS)

In [19]:
arr1, arr2 = np.split(array, [3], axis=1)
arr1

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Index 처리

In [20]:
l = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

l[0:2] #start~end-1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
l[:2,::2] #0~end-1

array([[1, 3],
       [5, 7]])

In [22]:
l[::2, ::2] #stride = 2

array([[ 1,  3],
       [ 9, 11]])

### logical indexing

In [23]:
l>8

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

-> index False, True 값으로 발현여부 index처리가능

In [24]:
l[l>8]

array([ 9, 10, 11, 12])

## numpy 연산

In [25]:
miles = np.array([1,2,3])
miles*1.6 #기본 = element-wise

array([1.6, 3.2, 4.8])

참고: .shape == (m,n) === m by n 행렬 의미

### 행렬곱

In [26]:
# A@B

## Array 메소드

In [27]:
a = [[1,2],[3,4],[5,6],[7,8]]
b = np.array(a)

b.sum()
b.min()
b.max(axis=1)

array([2, 4, 6, 8])

-> axis는 방향을 의미,  
axis=1: 열이 나아가는 방향  
1vs2  
3vs4  
...

# #1 Perceptron 구현

In [28]:
from numpy import *

# init setting
data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

w = random.rand(3)
c = 0.2
n  = 10

In [29]:
# Training
# Perceptron -> using Step activation

for epoch in range(n):
    for x,y in data:
        z = dot(x,w)
        
        # Activation = Step
        if z<0:
            a=0
        else:
            a=1
            
        dL_dA = a-y
        dA_dw = x
        delta = (-1)*dL_dA*dA_dw*c
        
        # stochastic, 빠른 수렴 기대
        w += delta
        
# Test
for x,_ in data:
    z = dot(x,w)
    if z<0:
        a=0
    else:
        a=1
    print(x[:2], z, a)
        

[0 0] -0.09701939514609376 0
[0 1] 0.4387605384668006 1
[1 0] 0.4924601744987705 1
[1 1] 1.0282401081116648 1


- Activation = Step  
=> a = 1 or 0  
  
- Loss = (1/2)*(Y-A)^2  
-> dL/dA = (A-Y)  
-> dA/dw = x  
=> delta = r*(A-Y)*x*(-1)  
  
- x에 bias term: always1 포함

# Pytorch

## tensor

ndarray의 일반화,  
numpy와 호환가능  
  
+ graphic faster(GPU성능 좋음)
+ Distribute operations(연산 분산가능)
+ 그래프 연산 트래킹

# Mechanics of Learning

: 실제로 러닝을 구현하는 방법

## Learning = 파라미터 추정

In [30]:
%matplotlib inline
import numpy as np

# pytorch 로딩
import torch
torch.set_printoptions(edgeitems=2, linewidth=75)

In [31]:
# input data
t_c = [0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0] # celcius
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4] # F(tend to be unknown)

t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

torch.tensor() 메소드로 tensor 형태로 데이터 변형  
  
t_c: 정확한 Celcius 값 = y  
t_u: 미지의 데이터값 = x

### Get Predicted Value

x 자체의 shape가 (n,1)이기 때문에,  
w의 차원은 1,1 = 스칼라  
그러므로 sample을 한 번에 처리해서 볼 예정

In [32]:
def model(t_u, w, b):
    return t_u * w + b # m개 1차 배열

In [33]:
def loss_fn(t_p, t_c):
    return ((t_c - t_p)**2).mean()

In [34]:
w = torch.ones((1))
b = torch.zeros((1))

t_p = model(t_u, w, b)
loss = loss_fn(t_p, t_c)
loss

tensor(1763.8848)

## Decrease Loss

### parameter tuning -- stochastic

In [35]:
delta = 0.1
r = 1e-2

loss_rate_of_w = (loss_fn(model(t_u, w + delta, b), t_c) - loss_fn(model(t_u, w-delta, b), t_c)) / 2*delta
w -= r*loss_rate_of_w

loss_rate_of_b = (loss_fn(model(t_u,w,b+delta), t_c) - loss_fn(model(t_u, w, b-delta), t_c)) / 2*delta
b -= r*loss_rate_of_b

### gradient 조정 // batch

In [36]:
# dL/dA
def dA_fn(t_p, t_c):
    return (2*(t_p-t_c))/t_p.size(0)

# dA/dw
def dw_fn(t_u, w, b):
    return t_u
    
# dA/db
def db_fn(t_u, w, b):
    return 1.0

def grad_fn(t_u, t_c, t_p, w, b):
    dloss_dtp = dA_fn(t_p, t_c)
    dloss_dw = dloss_dtp * dw_fn(t_u, w, b)
    dloss_db = dloss_dtp * db_fn(t_u, w, b)
    # 일률적 dw 조정
    return torch.stack([dloss_dw.sum(), dloss_db.sum()])

grad_fn(t_u, t_c, t_p, w, b)

tensor([4517.2964,   82.6000])

### Training_Loop

In [37]:
def training_loop(epochs, learning_rate, params, t_u, t_c):
    for epoch in range(epochs):
        w,b = params
        
        #forward
        t_p = model(t_u, t_c, w, b)
        loss = loss_fn(t_p, t_c)
        
        #backward -> get dparams
        dparams = grad_fn(t_u, t_c, t_p, w, b)
        #params tuning
        params -= dparams*learning_rate
        print('Epoch %d, Loss %f' % (epoch, float(loss)))

### Fancy one

In [38]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c, print_params=True):
    for epoch in range(1, n_epochs + 1): 
        t_p = model(t_u, *params) # <1>
        loss = loss_fn(t_p, t_c)
        grad = grad_fn(t_u, t_c, t_p, *params) # <2>
        params = params - learning_rate * grad
        
        if epoch in {1, 2, 3, 10, 11, 99, 100, 4000, 5000}: 
            print('Epoch %d, Loss %f' % (epoch, float(loss))) 
            if print_params:
                print(' Params:', params)
                print(' Grad: ', grad) 
            if epoch in {4, 12, 101}:
                print('...')
        if not torch.isfinite(loss).all():
            break  # <3>
    return params

In [39]:
training_loop(
    n_epochs = 100,
    learning_rate = 1e-2,
    params = torch.tensor([1.0, 0.0]),
    t_u = t_u,
    t_c = t_c
)

Epoch 1, Loss 1763.884766
 Params: tensor([-44.1730,  -0.8260])
 Grad:  tensor([4517.2964,   82.6000])
Epoch 2, Loss 5802484.500000
 Params: tensor([2568.4011,   45.1637])
 Grad:  tensor([-261257.4062,   -4598.9702])
Epoch 3, Loss 19408029696.000000
 Params: tensor([-148527.7344,   -2616.3931])
 Grad:  tensor([15109614.0000,   266155.6875])
Epoch 10, Loss 90901105189019073810297959556841472.000000
 Params: tensor([3.2144e+17, 5.6621e+15])
 Grad:  tensor([-3.2700e+19, -5.7600e+17])
Epoch 11, Loss inf
 Params: tensor([-1.8590e+19, -3.2746e+17])
 Grad:  tensor([1.8912e+21, 3.3313e+19])


tensor([-1.8590e+19, -3.2746e+17])

# 학습결과 해석

## #1문제: Loss가 너무 크다
gradient exploding..  
= 발산하는 문제

## 해결: step을 줄인다 == 수렴기대

In [40]:
training_loop(
    n_epochs = 100,
    learning_rate = 1e-5,
    params = torch.tensor([1.0, 0.0]),
    t_u = t_u,
    t_c = t_c
)

Epoch 1, Loss 1763.884766
 Params: tensor([ 9.5483e-01, -8.2600e-04])
 Grad:  tensor([4517.2964,   82.6000])
Epoch 2, Loss 1565.761353
 Params: tensor([ 0.9123, -0.0016])
 Grad:  tensor([4251.5220,   77.9184])
Epoch 3, Loss 1390.265503
 Params: tensor([ 0.8723, -0.0023])
 Grad:  tensor([4001.3838,   73.5123])
Epoch 10, Loss 611.527405
 Params: tensor([ 0.6509, -0.0065])
 Grad:  tensor([2617.3997,   49.1337])
Epoch 11, Loss 545.011597
 Params: tensor([ 0.6263, -0.0069])
 Grad:  tensor([2463.4038,   46.4211])
Epoch 99, Loss 29.116278
 Params: tensor([ 0.2341, -0.0165])
 Grad:  tensor([11.8088,  3.2363])
Epoch 100, Loss 29.114819
 Params: tensor([ 0.2340, -0.0165])
 Grad:  tensor([11.1109,  3.2240])


tensor([ 0.2340, -0.0165])

In [41]:
training_loop(
    n_epochs = 5000,
    learning_rate = 1e-4,
    params = torch.tensor([1.0, 0.0]),
    t_u = t_u,
    t_c = t_c,
    print_params = False
)

Epoch 1, Loss 1763.884766
Epoch 2, Loss 323.090515
Epoch 3, Loss 78.929634
Epoch 10, Loss 29.105247
Epoch 11, Loss 29.104168
Epoch 99, Loss 29.023582
Epoch 100, Loss 29.022667
Epoch 4000, Loss 25.691162
Epoch 5000, Loss 24.907743


tensor([ 0.2577, -1.4631])

## #2문제: 파라미터별로 Gradient 차이가 너무 크다
parameter 별로 scale이 달라서 생기는 문제  
한 params(W)의 변화가 다음 epoch에서 다른 params(b)의 변화에 너무 큰 영향을 미치는게 문제

## 해결: input normalizing
Why input, not parameter??  
bias scale = 일반 수  
params scale = x에 의해 좌우  
  
=> x를 표준화 -> bias와 스케일 일치, Gradient 차이 문제 해결  
= Parameter Balancing

In [42]:
t_un = 0.1*t_u

training_loop(
    n_epochs = 100,
    learning_rate = 1e-2,
    params = torch.tensor([1.0, 0.0]),
    t_u = t_un,
    t_c = t_c
)

Epoch 1, Loss 80.364342
 Params: tensor([1.7761, 0.1064])
 Grad:  tensor([-77.6140, -10.6400])
Epoch 2, Loss 37.574913
 Params: tensor([2.0848, 0.1303])
 Grad:  tensor([-30.8623,  -2.3864])
Epoch 3, Loss 30.871077
 Params: tensor([2.2094, 0.1217])
 Grad:  tensor([-12.4631,   0.8587])
Epoch 10, Loss 29.030489
 Params: tensor([ 2.3232, -0.0710])
 Grad:  tensor([-0.5355,  2.9295])
Epoch 11, Loss 28.941877
 Params: tensor([ 2.3284, -0.1003])
 Grad:  tensor([-0.5240,  2.9264])
Epoch 99, Loss 22.214186
 Params: tensor([ 2.7508, -2.4910])
 Grad:  tensor([-0.4453,  2.5208])
Epoch 100, Loss 22.148710
 Params: tensor([ 2.7553, -2.5162])
 Grad:  tensor([-0.4446,  2.5165])


tensor([ 2.7553, -2.5162])

In [43]:
params = training_loop(
    n_epochs = 5000,
    learning_rate = 1e-2,
    params = params,
    t_u = t_un,
    t_c = t_c,
    print_params = False
)

params

NameError: name 'params' is not defined

### Argument Unpacking
params = (a,b) -> fn(c, d, *params)

## Let's Visualize
-> using pyplot

plt _ 의존  
.plot() x,y 입력값에 대해 그래프 그려줌  
-> x,y는 numpy여야한다.  
=> tensor.numpy()로 입력

In [44]:
from matplotlib import pyplot as plt

# after learning value
t_p = model(t_un, *params)

fig = plt.figure(dpi=600)
# x,y 라벨 설정
plt.xlabel("Temperature (F)")
plt.ylabel("Temperature (C)")

# inferenced
plt.plot(t_u.numpy(), t_p.numpy())
# data 'o' to make dot
plt.plot(t_u.numpy(), t_c.numpy(), 'o')

NameError: name 'params' is not defined

# autograd == Pytorch cal Gradient(Back-propagation)
: params by params  
grad는 tensor에 프로퍼티로 저장할 수 있다.  

### tensor.grad 활용 세팅

In [45]:
params = torch.tensor([1.0, 0.0], requires_grad = True) # can tracking in Loss

params.grad is None

True

### loss.backward() 활용
-> params.grad 저장 후 알아서 핸들링

In [46]:
loss = loss_fn(model(t_u,*params), t_c)
loss.backward()

params.grad

tensor([4517.2969,   82.6000])

### backward란?
기울기계산 -> 리프노드에 기울기 쌓아(단순합) 저장  
=> 누적계산되지 않으려면???  
parmas.grad를 parameter tuning 이후에 지워줘야한다.

In [47]:
params.grad.zero_() # 다음 합 = 다음 derivative

tensor([0., 0.])

## Training Loop by autograd

In [48]:
def training_loop(n_epochs, learning_rate, params, t_u, t_c, print_params=True):
    for epoch in range(1, n_epochs + 1): 
        if params.grad is not None:
            params.grad.zero_()
        
        t_p = model(t_u, *params) # <1>
        loss = loss_fn(t_p, t_c)
        
        #grad = grad_fn(t_u, t_c, t_p, *params) # <2>
        loss.backward()
        with torch.no_grad():
            params -= learning_rate * params.grad
            
        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, loss))
                
        if not torch.isfinite(loss).all():
            break  # <3>
            
    return params

In [49]:
training_loop(
    n_epochs = 5000,
    learning_rate = 1e-2,
    params = torch.tensor([1.0,0.0], requires_grad = True),
    t_u = t_un,
    t_c = t_c,
)

Epoch 500, Loss 7.860115
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957698
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927679
Epoch 4500, Loss 2.927652
Epoch 5000, Loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)

## with 키워드
: critical region에 접근할 때 사용,  
객체의 라이프사이클(생성 >> 사용 >> 소멸)을 설계  
with torch.no_grad():  
-> no.grad() 안에는  
\__enter__  
\__fn__  
\__exit__  

=> 순서에 맞게 실행  

## no_grad() 함수가 의미하는 것
requires_grad = True로 설정시 params.grad에 대한 모든 연산을 트래킹하게 설정되어있다.  
하지만 연산이 트래킹될 필요가 없는 경우에는 grad의 연산과정을 트래킹하지 않도록 no_grad()로 설정할 수 있다.  
일례로 단순히 gradient descent를 할 경우, 각 연산은 한 번 쓰이고 끝나므로 keep watching할 필요가 없지만,  
optimizer를 사용하여 자동으로 additionally하게 연산을 추가해야하는 경우 해당 grad operation을 다시 들여다볼 필요가 있으므로, no_grad()가 아닌 범위에서 수행되는 것이다

# Optimizers
: operate when backward()

### Optimizer.step()
적용된 grad에 optimizer value 적용해서 처리  
=> param 직접 바꿀 필요 없이 optimizer 적용된 값으로 조정
=> parameter tuning을 optimizer가 알아서 처리한다는 의미
### Optimizer.grad_zero()
이전에 사용된 grad 초기화, clear -> with torch.no_grad(): or .grad.zero_() 같은거 안해도 된다.

In [50]:
import torch.optim as optim

params = torch.tensor([1.0,0.0], requires_grad = True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)

t_p = model(t_u, *params)

loss = loss_fn(t_p, t_c)
loss.backward()
optimizer.step()

params.grad

tensor([4517.2969,   82.6000])

In [51]:
import torch.optim as optim

params = torch.tensor([1.0,0.0], requires_grad = True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

t_p = model(t_un, *params)

loss = loss_fn(t_p, t_c)
optimizer.zero_grad()
loss.backward()
optimizer.step()

params.grad

tensor([-77.6140, -10.6400])

In [52]:
def training_loop(n_epochs, optimizer, params, t_u, t_c, print_params=True):
    for epoch in range(1, n_epochs + 1): 
        
        t_p = model(t_u, *params) # <1>
        loss = loss_fn(t_p, t_c)
        
        #grad = grad_fn(t_u, t_c, t_p, *params) # <2>
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
            
        if epoch % 500 == 0:
            print('Epoch %d, Loss %f' % (epoch, loss))
            
    return params

In [53]:
params = torch.tensor([1.0,0.0], requires_grad = True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr = learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    t_u = t_un,
    t_c = t_c
)

Epoch 500, Loss 7.860115
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957698
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927679
Epoch 4500, Loss 2.927652
Epoch 5000, Loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)

# 교차검증
: training & validation  
-> overfitting 되어 있는지 측정가능  
training 결과가 validation 결과보다 많이 좋다면 overfitting된 상태  
-> Data 늘리거나 Reg 사용

### make validation set
tensor 자체를 분리하지 않는다. (랜덤하게 추출하는 방법을 여러번 사용하기 위해서인듯)  
-> 그 때 그 때 index tensor를 만들어서 관리 

In [65]:
# 20% 비율로 설정
m = t_u.shape[0]
n_val = int(m*0.2)


shuffled_index = torch.randperm(m)
train_index = shuffled_index[:-n_val]
val_index = shuffled_index[-n_val:]

train_t_u = t_u[train_index]
train_t_c = t_u[train_index]
val_t_u = t_u[val_index]
val_t_c = t_c[val_index]

train_t_un = 0.1*train_t_u
val_t_un = 0.1*train_t_u

### training loop 업데이트

In [74]:
def training_loop(n_epochs, optimizer, params, train_t_u, train_t_c, val_t_u, val_t_c):
    for epoch in range(n_epochs):
        #각각 forwarding & get loss
        train_p = model(train_t_u, *params)
        train_loss = loss_fn(train_p, train_t_c)
        val_p = model(val_t_u, *params)
        val_loss = loss_fn(val_p, val_t_c)
        
        # train_loss만 학습에 사용
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()
        
        if epoch <=3 or epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"f" Validation loss {val_loss.item():.4f}")

### inference 모드에서 grad 계산 방지

In [78]:
with torch.set_grad_enabled(False):
    t_p = model(t_u, *params)
    loss = loss_fn(t_p, t_c)

# Keyword 정리
- requires_grad = True
- TENSOR.grad.zero_()
- with torch.no_grad():
- optimizer.zero_grad()
- torch.optim as optim
- optim.SGD([parmas], lr)
- optimizer.step()
- int(A*B)
- tensor[tensor(index or bool)]
- torch.randperm(m) 0~m index permutating